skos:
  distributie_pad: ../resources/be/vlaanderen/omgeving/data/id/conceptscheme/chemische_stof/
  distributie_naam: emissie
  jsonld_source: ../resources/source/codelijst_context.json
  csv_source: ../resources/source/codelijst_source.csv
dcat:
  distributie_pad_catalog : ../resources/be/vlaanderen/omgeving/data/id/catalog/codelijst-chemische_stof/
  distributie_pad_dataset : ../resources/be/vlaanderen/omgeving/data/id/dataset/codelijst-chemische_stof/
  jsonld_source : ../resources/source/catalog_context.json
  dataset_source : ../resources/source/dataset_source.csv
  catalog_source : ../resources/source/catalog_source.csv
